version: '3.1'
services:
  server:
    container_name: 'eliverd_server'
    ports:
      - '8000:8000'
    command: sh ./entrypoint.sh
    environment:
      DB_NAME: eliverd
      DB_USER: root
      DB_PW: Wb4H9nn542
      DB_HOST: donote.co
      DB_PORT: 3306
    restart: on-failure
    image: startergate/eliverd-api